spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_PROD_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
  ssl:
    enabled: false
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: ${SESSION_COOKIE_NAME}
        domain: ${SESSION_COOKIE_DOMAIN}
        secure: true
        same-site: None
      timeout: 24h # TODO: 테스트 완료 후 제거

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    servers:
      - url: ${SWAGGER_SERVER_URL}
        description: Production Server

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.9, 0.99
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.acquire: true
        method.timed: true
