spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:${MYSQL_PROD_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD}}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: ${FLYWAY_BASELINE_VERSION:1}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp-auth: true
    starttls-enable: true
    starttls-required: true


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:${DDL_AUTO:validate}}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

server:
  port: 8080
  ssl:
    enabled: false
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: ${SESSION_COOKIE_NAME}
        domain: ${SESSION_COOKIE_DOMAIN}
        secure: true
        same-site: None
      timeout: 24h # TODO: 테스트 완료 후 제거

app:
  cors:
    allowed-origin:
      - "https://docsa.o-r.kr"
      - "https://docsa-4hh.pages.dev"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    servers:
      - url: ${SWAGGER_SERVER_URL}
        description: Production Server


decorator:
  datasource:
    enabled: false

logging:
  level:
    root: WARN
    io.ejangs.docsa: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.springframework: WARN
    org.mongodb.driver: WARN
    com.zaxxer.hikari: WARN
    net.ttddyy.dsproxy.listener: WARN
