spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_PROD_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  mail:
    host: mailpit
    port: 1025
    username: ${MAIL_USERNAME:test@docsa.com}
    password:
    smtp-auth: false
    starttls-enable: false
    starttls-required: false


  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

server:
  port: 8080
  ssl:
    enabled: false
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: ${SESSION_COOKIE_NAME}
        domain: ${SESSION_COOKIE_DOMAIN}
        secure: true
        same-site: None
      timeout: 24h # TODO: 테스트 완료 후 제거

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    servers:
      - url: ${SWAGGER_SERVER_URL}
        description: Production Server
