spring:
  profiles:
    active: local

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGO_URI}}

  mail:
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.9, 0.99
      percentiles-histogram:
        http.server.requests: true
        hikaricp.connections.acquire: true
        method.timed: true

auth:
  signup-code-cache-name: signupCodeCache
  passcode-cache-name: passCodeCache
  pwd-reset-code-cache-name: pwdResetCodeCache
  resend-limit-cache-name: resendLimitCache

default:
  branch: main

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}
      presigned-expire-minutes: ${AWS_PRESIGNED_EXPIRE_MIN:5}
      public-base-url: ${CDN_URL}

mongo:
  delete:
    outbox:
      worker:
        enabled: true
        fixed-delay: PT1M
        initial-delay: PT0S

s3:
  delete:
    outbox:
      worker:
        enabled: true
        fixed-delay: PT1M
        initial-delay: PT0S

domain:
  event:
    outbox:
      worker:
        enabled: true
        fixed-delay: PT10S
        initial-delay: PT5S
