spring:
  profiles:
    active: local

  data:
    mongodb:
      uri: ${MONGO_URI}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp-auth: true
    starttls-enable: true
    starttls-required: true
    connection-timeout: 5000
    timeout: 5000
    write-timeout: 5000

auth:
  signup-code-cache-name: signupCodeCache
  passcode-cache-name: passCodeCache
  pwd-reset-code-cache-name: pwdResetCodeCache
  resend-limit-cache-name: resendLimitCache

default:
  branch: main