user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
        worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
        default_type application/octet-stream;
	
	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
			'$status $body_bytes_sent "$http_referer" '
			'"$http_user_agent" "$http_x_forwarded_for"';
	error_log /var/log/nginx/error.log warn;
        access_log /var/log/nginx/access.log main;

	resolver 127.0.0.11 valid=10s ipv6=off;

	upstream docsa_stg_app {
		zone docsa_stg_app 64k;
		server app:8080 resolve;
	}

	upstream docsa_stg_management {
		zone docsa_stg_management 64k;
		server app:9091 resolve;
	}

	upstream docsa_stg_mailpit {
		zone docsa_stg_mailpit 64k;
		server mailpit:8025 resolve;
	}

  server {
          listen 80;
          server_name stg.api.docsa.o-r.kr;

		location ^~ /.well-known/acme-challenge/ {
			root /var/www/certbot;
		}
		
		location / {return 301 https://$host$request_uri; }
	}

	server {
		listen 443 ssl http2;
		server_name stg.api.docsa.o-r.kr;

		ssl_certificate /etc/letsencrypt/live/stg.api.docsa.o-r.kr/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/stg.api.docsa.o-r.kr/privkey.pem;

		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers HIGH:!aNULL:!MD5;
		ssl_prefer_server_ciphers on;

		ssl_session_cache shared:SSL:10m;
		ssl_session_timeout 1d;

		location = /actuator/health {
			proxy_pass http://docsa_stg_management;

			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location / {
			proxy_pass http://docsa_stg_app;
			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}


		location /grafana/ {
			return 302 https://api.docsa.o-r.kr$request_uri;
		}


		location /mailpit/ {
			proxy_pass http://docsa_stg_mailpit;

			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_set_header Host              $host;
			proxy_set_header X-Real-IP         $remote_addr;
			proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location = /actuator/prometheus { return 404; }

  }
}
