name: "✨ Design"
description: "CSS 등 사용자 UI 디자인 변경"
labels: ["test"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 디자인에 대한 설명을 작성해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.