name: "✨ Docs"
description: "문서 수정"
labels: ["docs"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 새로운 문서에 대한 설명을 작성해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.